import Services from "./Services";

export const metadata = {
  title: "Our Services - Aplus Advertising Limited",
  description:
    "A Plus Advertising Limited - Expert web design, eCommerce, SEO & digital marketing to grow your business online",
  keywords: [
    "Website Design Bangladesh",
    "Custom Website Development BD",
    "Affordable Website Design Dhaka",
    "Responsive Website Design Bangladesh",
    "Business Website Design Service BD",
    "Portfolio Website Design Bangladesh",
    "WordPress",
    "Website Developer BD",
    "Corporate Website Design Bangladesh",
    "Website Redesign and Fixing Service BD",
    "Best Website Design Agency Bangladesh",
    "Ecommerce Website Design Bangladesh",
    "WooCommerce Website Development BD",
    "Shopify to WordPress Migration BD",
    "Best Ecommerce Store Builder Bangladesh",
    "Ecommerce SEO Optimization BD",
    "Payment Gateway Integration Bangladesh",
    "Online Store Design BD",
    "WooCommerce Expert Bangladesh",
    "Ecommerce Website Maintenance Bangladesh",
    "Custom Ecommerce Solution BD",
    "Landing Page Design Services BD",
    "Single Page Website Bangladesh",
    "Personal Portfolio Website BD",
    "One Page Responsive Design BD",
    "Conversion Optimized Landing Page Bangladesh",
    "Creative Portfolio Website Designer BD",
    "Fast Loading Landing Page BD",
    "Portfolio Website for Freelancers BD",
    "Business Landing Page Bangladesh",
    "Affordable Portfolio Website Bangladesh",
    "News Portal Website Design Bangladesh",
    "Online Newspaper Website BD",
    "Blog Website Development Bangladesh",
    "WordPress Blog Setup BD",
    "Magazine Website Designer Bangladesh",
    "News Portal Maintenance BD",
    "Fast News Website Design BD",
    "Responsive Blog Design Bangladesh",
    "News Portal WordPress Developer BD",
    "Affordable Blog Website Bangladesh",
    "Medical Website Design Bangladesh",
    "Clinic Website Development BD",
    "Doctor Portfolio Website Bangladesh",
    "Hospital Website Design Service BD",
    "Healthcare Website Developer BD",
    "Medical SEO Services Bangladesh",
    "Appointment Booking Website Bangladesh",
    "Pharmacy Website Design BD",
    "Clinic Management Website Bangladesh",
    "Medical Website SEO Optimization BD",
    "SEO Services Bangladesh",
    "On-Page SEO Expert BD",
    "Off-Page SEO Bangladesh",
    "Local SEO Bangladesh",
    "Affordable SEO Service BD",
    "SEO Optimization Company BD",
    "Website Ranking Expert Bangladesh",
    "Google Ranking Services BD",
    "WordPress SEO Specialist BD",
    "Technical SEO Audit Bangladesh",
    "Content Writing Service Bangladesh",
    "SEO Optimized Content Writer BD",
    "Website Copywriting Service BD",
    "Blog Content Writing Bangladesh",
    "Affordable Content Writing BD",
    "Professional Article Writing Service BD",
    "Digital Marketing Content BD",
    "Web Page Content Writing Bangladesh",
    "Product Description Writer BD",
    "SEO Copywriting Bangladesh",
    "Facebook Boosting Agency BD",
    "Social Media Marketing Bangladesh",
    "Digital Marketing Service BD",
    "Facebook Ads Expert Bangladesh",
    "Google Ads Management BD",
    "Social Media Strategy Bangladesh",
    "Affordable FB Boosting BD",
    "Instagram Marketing Bangladesh",
    "YouTube Promotion Service BD",
    "Online Brand Promotion Bangladesh",
    "WordPress Website Design Bangladesh",
    "WooCommerce Development BD",
    "WordPress Plugin Customization BD",
    "WordPress Theme Design Dhaka",
    "Custom WordPress Developer BD",
    "Affordable WordPress Maintenance Bangladesh",
    "WordPress Speed Optimization BD",
    "WordPress Security Expert Bangladesh",
    "WordPress Bug Fixing Service BD",
    "WordPress Migration Service BD",
    "Website Fixing Service Bangladesh",
    "Website Speed Optimization BD",
    "Broken Website Repair BD",
    "Website Maintenance Expert Bangladesh",
    "Affordable Website Support BD",
    "WordPress Error Fixing BD",
    "Website Bug Fix Bangladesh",
    "Site Security Update BD",
    "Monthly Website Maintenance BD",
    "Website Update & Backup Service BD",
  ],
};

export default function Page() {
  return <Services />;
}
