import Project from "./Project";

export const metadata = {
  title: "Our Projects - Aplus Advertising Limited",
  description:
    "A Plus Advertising Limited - Expert web design, eCommerce, SEO & digital marketing to grow your business online",
  keywords: [
  "A Plus Advertising Limited Projects",
  "A Plus Advertising Limited Portfolio",
  "A Plus Advertising Demo Websites",
  "Website Design Samples Bangladesh",
  "Ecommerce Website Demo Bangladesh",
  "Business Website Examples",
  "Portfolio Website Demo",
  "Landing Page Design Bangladesh",
  "SEO Optimized Website Examples",
  "Creative Web Development Projects",
  "WordPress Website Design Samples",
  "WooCommerce Website Demo",
  "Responsive Website Design Bangladesh",
  "Professional Web Agency Projects",
  "Best Website Design Company Bangladesh",
  "Top Web Development Agency Bangladesh",
  "Digital Agency Portfolio Bangladesh",
  "Custom Website Development Showcase",
  "Business Website Portfolio Bangladesh",
  "Modern Web Design Gallery",
  "Creative Website Development in Bangladesh",
  "Ecommerce Website Design Samples",
  "Corporate Website Examples",
  "Medical Website Demo Bangladesh",
  "Educational Website Design Samples",
  "Restaurant Website Demo Bangladesh",
  "Real Estate Website Design Bangladesh",
  "Construction Company Website Examples",
  "Blog and News Portal Demo Bangladesh",
  "Affordable Web Design Bangladesh",
  "A Plus Advertising Limited Web Design",
  "Web Design Inspiration Bangladesh",
  "Website Gallery Bangladesh",
  "Best Web Design Demo Bangladesh",
  "A Plus Advertising Website Samples",
  "SEO Friendly Website Design",
  "Fast Loading Website Development Bangladesh",
  "Bangladesh Web Agency Showcase",
  "A Plus Advertising Limited Creative Works",
  "A Plus Advertising Limited Projects Gallery",
  "WordPress Web Development Bangladesh",
  "Bangladesh Top Rated Web Agency",
  "Web Design Portfolio Bangladesh",
  "Responsive Web Agency Bangladesh",
  "A Plus Advertising Professional Web Design",
  "Premium Web Development Bangladesh",
  "Top Ranked Website Design Bangladesh",
  "#1 Web Development Agency Bangladesh",
  "Modern Website Design Showcase"
],
};

export default function Page() {
  return <Project />;
}